name = "traffic-splitting-worker"
main = "src/index.ts"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_compat"]

[vars]
BACKEND_BASE_URL = "https://lgg-traffic-splitting-api.onrender.com"
INGEST_API_KEY = "6c9f91e9500e40ae4832fbf081940e05e299d237cd7efb07"
ASSIGNMENT_TTL_SECONDS = "2592000"
SENTRY_ENVIRONMENT = "production"
SENTRY_TRACES_SAMPLE_RATE = "0.2"

[[kv_namespaces]]
binding = "EXPERIMENTS_KV"
id = "462cd99ae90048f5828a2ee6bc4aa7e5"
preview_id = "462cd99ae90048f5828a2ee6bc4aa7e5"

[[queues.producers]]
binding = "IMPRESSIONS_QUEUE"
queue = "traffic-splitting-impressions"

[[queues.consumers]]
queue = "traffic-splitting-impressions"
max_batch_size = 50
max_batch_timeout = 5
